DROP SEQUENCE orders_id_seq;

CREATE SEQUENCE orders_id_seq START WITH 300000 INCREMENT BY 1;
ALTER TABLE dbo.orders ALTER COLUMN O_ID SET DEFAULT NEXTVAL('orders_id_seq');
ALTER AUTHORIZATION ON SEQUENCE::orders_id_seq TO azureuser;
ALTER TABLE dbo.orders ALTER COLUMN O_ID ADD GENERATED ALWAYS AS IDENTITY;

DROP SEQUENCE orderline_id_seq;

CREATE SEQUENCE orderline_id_seq START WITH 3000000 INCREMENT BY 1;
ALTER TABLE dbo.orderline ALTER COLUMN OL_ID SET DEFAULT NEXTVAL('orderline_id_seq');
ALTER AUTHORIZATION ON SEQUENCE::orderline_id_seq TO azureuser;
ALTER TABLE dbo.orderline ALTER COLUMN OL_ID ADD GENERATED ALWAYS AS IDENTITY;


