[TP-1]
sql = "INSERT INTO orderline VALUES (DEFAULT, ?,?,?,?,?);"

[TP-2]
sql = [
    "SELECT O_ID, O_C_ID, O_TOTALAMOUNT, O_UPDATEDDATE FROM orders WHERE o_status='unpaid' ORDER BY RANDOM() LIMIT 1",
    "UPDATE customer SET C_CREDIT=?, C_UPDATEDDATE=? WHERE C_ID=?",
    "UPDATE orders SET O_UPDATEDDATE=? WHERE O_ID=?"
]

[TP-3]
sql = "SELECT O_ID, O_DATE, O_STATUS FROM orders WHERE O_C_ID = ? order by O_UPDATEDDATE desc limit 1;"