[TP-1]
sql = "INSERT INTO dbo.orderline(OL_O_ID, OL_P_ID, OL_QUANTITY, OL_TOTALAMOUNT, OL_UPDATEDDATE) VALUES (?,?,?,?,?);"

[TP-2]
sql = [
    "SELECT TOP 1 O_ID, O_C_ID, O_TOTALAMOUNT, O_UPDATEDDATE FROM orders WHERE o_status='unpaid' ORDER BY NEWID()",
    "UPDATE customer SET C_CREDIT=?, C_UPDATEDDATE=? WHERE C_ID=?",
    "UPDATE orders SET O_UPDATEDDATE=? WHERE O_ID=?"
]

[TP-3]
sql = "SELECT TOP 1 O_ID, O_DATE, O_STATUS FROM dbo.orders WHERE O_C_ID = ? order by O_UPDATEDDATE desc;"